prometheus:
  managed: False

  service_user: 'prometheus'
  service_group: 'prometheus'

  server:
    version: '2.6.0'
    source_fmt: 'https://github.com/prometheus/prometheus/releases/download/v{version}/prometheus-{version}.linux-{arch}.tar.gz'
    source_hash_fmt: 'https://github.com/prometheus/prometheus/releases/download/v{version}/sha256sums.txt'

    config:
      global:
        scrape_interval: 60s
        evaluation_interval: 60s

      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']

  node_exporter:
    version: '0.17.0'
    source_fmt: 'https://github.com/prometheus/node_exporter/releases/download/v{version}/node_exporter-{version}.linux-{arch}.tar.gz'
    source_hash_fmt: 'https://github.com/prometheus/node_exporter/releases/download/v{version}/sha256sums.txt'
    flags: []

  <cpuarch>:
    x86_64:
      arch: 'amd64'

  <os_family>:
    Debian:
      base_path: '/opt/prometheus'
