#!/bin/sh
# Managed by SaltStack

cat <<'EOF'
 ____                   ____
/ ___| _ __   __ _ _ __/ ___|  ___ _ ____   __
\___ \| '_ \ / _` | '_ \___ \ / _ \ '__\ \ / /
 ___) | | | | (_| | |_) |__) |  __/ |   \ V /
|____/|_| |_|\__,_| .__/____/ \___|_|    \_/
                  |_|

EOF

printf "Welcome to %s (%s).\n\n" "$(/usr/bin/lsb_release -s -d)" "$(uname -r)"
